_BASE_: "../../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  RETINANET:
    NUM_CLASSES: 10
DATASETS:
  TRAIN: ("bdd100k_train",)
  TEST: ("bdd100k_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (36000, 48000,)
  MAX_ITER: 52500
INPUT:
  MIN_SIZE_TRAIN: (800,)
  CROP:
    ENABLED: True
OUTPUT_DIR: "checkpoints/bdd100k/retinanet/retinanet_r_101_fpn_1x_crop"