_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/model_final_a54504.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("bdd100k_train_ins_seg",)
  TEST: ("bdd100k_val_ins_seg",)
