_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  MASK_ON: False
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 10
DATASETS:
  TRAIN: ("bdd100k_train",)
  TEST: ("bdd100k_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
INPUT:
  MIN_SIZE_TRAIN: (800,)
  CROP:
    ENABLED: True
OUTPUT_DIR: "./checkpoints/bdd100k/d/faster_rcnn/faster_rcnn_x_101_32x8d_fpn_2x_crop"
