_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 10
DATASETS:
  TRAIN: ("bdd100k_train",)
  TEST: ("bdd100k_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
INPUT:
  MIN_SIZE_TRAIN: (800,)
  CROP:
    ENABLED: True
OUTPUT_DIR: "./checkpoints/bdd100k/d/faster_rcnn/faster_rcnn_r_101_fpn_2x_crop"
