_BASE_: "../../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 10
DATASETS:
  TRAIN: ("bdd100k_train",)
  TEST: ("bdd100k_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (36000, 48000,)
  MAX_ITER: 52500
INPUT:
  MIN_SIZE_TRAIN: (800,)
  CROP:
    ENABLED: True
OUTPUT_DIR: "./checkpoints/bdd100k/d/faster_rcnn/faster_rcnn_r_50_c4_1x_crop"
