_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "BddMultitaskModel"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  SEM_SEG_HEADS:
    DRIVABLE_HEAD:
      NAME: "GeneralSemSegFPNHead"
      NUM_CLASSES: 3
      LOSS_ID: "drivable"
DATASETS:
  TRAIN: ("bdd100k_train_drivable",)
  TEST: ("bdd100k_val_drivable",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (36000, 48000,)
  MAX_ITER: 52500
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
TASKS: ("drivable",)
OUTPUT_DIR: "./checkpoints/bdd100k/r/resnet/r_50_fpn_1x"
